a=int(input("이차항의 계수를 입력해 주세요."))
b=int(input("일차항의 계수를 입력해 주세요."))
c=int(input("이차항의 계수를 입력해 주세요."))
x1=(-b+(b**2-4*a*c)**0.5)/(2*a)
x2=(-b-(b**2-4*a*c)**0.5)/(2*a)
print(f"해:{x1},{x2}")
print(f"x1 + x2 = {x1+x2}") 
print(f"x1 * x2 = {x1*x2}")